version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sootio
    container_name: sootio
    ports:
      - "${PORT:-6907}:${PORT:-6907}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
    restart: unless-stopped
