version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sootio
    container_name: sootio
    ports:
      - "${PORT:-6907}:${PORT:-6907}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - node_modules:/app/node_modules
    command: ["node", "server.js"]
    restart: unless-stopped

volumes:
  node_modules:
